// Built-in exercise library, seeded into IndexedDB on first run. Ids are
// fixed/stable so exports/imports and references stay valid across sessions.
// [id, name, category, equipment, [ [muscle, role], ... ]]
export const SEED_EXERCISES = [
  // ---- PUSH: chest / shoulders / triceps ----
  [1, 'Barbell Bench Press', 'push', 'barbell', [['chest', 'primary'], ['triceps', 'secondary'], ['shoulders', 'secondary']]],
  [2, 'Incline Barbell Bench Press', 'push', 'barbell', [['chest', 'primary'], ['shoulders', 'secondary'], ['triceps', 'secondary']]],
  [3, 'Decline Barbell Bench Press', 'push', 'barbell', [['chest', 'primary'], ['triceps', 'secondary']]],
  [4, 'Dumbbell Bench Press', 'push', 'dumbbell', [['chest', 'primary'], ['triceps', 'secondary'], ['shoulders', 'secondary']]],
  [5, 'Incline Dumbbell Press', 'push', 'dumbbell', [['chest', 'primary'], ['shoulders', 'secondary']]],
  [6, 'Dumbbell Flyes', 'push', 'dumbbell', [['chest', 'primary']]],
  [7, 'Cable Crossover', 'push', 'cable', [['chest', 'primary']]],
  [8, 'Push-Up', 'push', 'bodyweight', [['chest', 'primary'], ['triceps', 'secondary'], ['shoulders', 'secondary'], ['core', 'secondary']]],
  [9, 'Chest Dip', 'push', 'bodyweight', [['chest', 'primary'], ['triceps', 'secondary']]],
  [10, 'Overhead Barbell Press', 'push', 'barbell', [['shoulders', 'primary'], ['triceps', 'secondary']]],
  [11, 'Dumbbell Shoulder Press', 'push', 'dumbbell', [['shoulders', 'primary'], ['triceps', 'secondary']]],
  [12, 'Arnold Press', 'push', 'dumbbell', [['shoulders', 'primary'], ['triceps', 'secondary']]],
  [13, 'Lateral Raise', 'push', 'dumbbell', [['shoulders', 'primary']]],
  [14, 'Front Raise', 'push', 'dumbbell', [['shoulders', 'primary']]],
  [15, 'Rear Delt Fly', 'push', 'dumbbell', [['shoulders', 'primary'], ['back', 'secondary']]],
  [16, 'Cable Lateral Raise', 'push', 'cable', [['shoulders', 'primary']]],
  [17, 'Machine Shoulder Press', 'push', 'machine', [['shoulders', 'primary'], ['triceps', 'secondary']]],
  [18, 'Triceps Pushdown', 'push', 'cable', [['triceps', 'primary']]],
  [19, 'Overhead Triceps Extension', 'push', 'dumbbell', [['triceps', 'primary']]],
  [20, 'Skull Crushers', 'push', 'barbell', [['triceps', 'primary']]],
  [21, 'Close-Grip Bench Press', 'push', 'barbell', [['triceps', 'primary'], ['chest', 'secondary']]],
  [22, 'Triceps Dip', 'push', 'bodyweight', [['triceps', 'primary'], ['chest', 'secondary']]],

  // ---- PULL: back / biceps / traps ----
  [23, 'Barbell Row', 'pull', 'barbell', [['back', 'primary'], ['biceps', 'secondary']]],
  [24, 'Pendlay Row', 'pull', 'barbell', [['back', 'primary']]],
  [25, 'Dumbbell Row', 'pull', 'dumbbell', [['back', 'primary'], ['biceps', 'secondary']]],
  [26, 'T-Bar Row', 'pull', 'machine', [['back', 'primary']]],
  [27, 'Seated Cable Row', 'pull', 'cable', [['back', 'primary'], ['biceps', 'secondary']]],
  [28, 'Lat Pulldown', 'pull', 'cable', [['back', 'primary'], ['biceps', 'secondary']]],
  [29, 'Pull-Up', 'pull', 'bodyweight', [['back', 'primary'], ['biceps', 'secondary']]],
  [30, 'Chin-Up', 'pull', 'bodyweight', [['back', 'primary'], ['biceps', 'secondary']]],
  [31, 'Single-Arm Dumbbell Row', 'pull', 'dumbbell', [['back', 'primary']]],
  [32, 'Face Pull', 'pull', 'cable', [['shoulders', 'primary'], ['back', 'secondary'], ['traps', 'secondary']]],
  [33, 'Barbell Shrug', 'pull', 'barbell', [['traps', 'primary']]],
  [34, 'Dumbbell Shrug', 'pull', 'dumbbell', [['traps', 'primary']]],
  [35, 'Barbell Curl', 'pull', 'barbell', [['biceps', 'primary']]],
  [36, 'Dumbbell Curl', 'pull', 'dumbbell', [['biceps', 'primary']]],
  [37, 'Hammer Curl', 'pull', 'dumbbell', [['biceps', 'primary'], ['forearms', 'secondary']]],
  [38, 'Preacher Curl', 'pull', 'barbell', [['biceps', 'primary']]],
  [39, 'Cable Curl', 'pull', 'cable', [['biceps', 'primary']]],
  [40, 'Concentration Curl', 'pull', 'dumbbell', [['biceps', 'primary']]],
  [41, 'Reverse Curl', 'pull', 'barbell', [['forearms', 'primary'], ['biceps', 'secondary']]],

  // ---- LEGS: quads / hamstrings / glutes / calves ----
  [42, 'Barbell Back Squat', 'legs', 'barbell', [['quads', 'primary'], ['glutes', 'secondary'], ['hamstrings', 'secondary']]],
  [43, 'Front Squat', 'legs', 'barbell', [['quads', 'primary'], ['glutes', 'secondary']]],
  [44, 'Goblet Squat', 'legs', 'dumbbell', [['quads', 'primary'], ['glutes', 'secondary']]],
  [45, 'Leg Press', 'legs', 'machine', [['quads', 'primary'], ['glutes', 'secondary']]],
  [46, 'Walking Lunge', 'legs', 'dumbbell', [['quads', 'primary'], ['glutes', 'secondary'], ['hamstrings', 'secondary']]],
  [47, 'Bulgarian Split Squat', 'legs', 'dumbbell', [['quads', 'primary'], ['glutes', 'secondary']]],
  [48, 'Leg Extension', 'legs', 'machine', [['quads', 'primary']]],
  [49, 'Romanian Deadlift', 'legs', 'barbell', [['hamstrings', 'primary'], ['glutes', 'secondary'], ['back', 'secondary']]],
  [50, 'Conventional Deadlift', 'legs', 'barbell', [['hamstrings', 'primary'], ['glutes', 'primary'], ['back', 'secondary'], ['traps', 'secondary']]],
  [51, 'Lying Leg Curl', 'legs', 'machine', [['hamstrings', 'primary']]],
  [52, 'Seated Leg Curl', 'legs', 'machine', [['hamstrings', 'primary']]],
  [53, 'Hip Thrust', 'legs', 'barbell', [['glutes', 'primary'], ['hamstrings', 'secondary']]],
  [54, 'Glute Bridge', 'legs', 'bodyweight', [['glutes', 'primary']]],
  [55, 'Cable Pull-Through', 'legs', 'cable', [['glutes', 'primary'], ['hamstrings', 'secondary']]],
  [56, 'Standing Calf Raise', 'legs', 'machine', [['calves', 'primary']]],
  [57, 'Seated Calf Raise', 'legs', 'machine', [['calves', 'primary']]],
  [58, 'Hip Abduction Machine', 'legs', 'machine', [['glutes', 'primary']]],

  // ---- CORE ----
  [59, 'Plank', 'core', 'bodyweight', [['core', 'primary']]],
  [60, 'Side Plank', 'core', 'bodyweight', [['core', 'primary']]],
  [61, 'Hanging Leg Raise', 'core', 'bodyweight', [['core', 'primary']]],
  [62, 'Cable Crunch', 'core', 'cable', [['core', 'primary']]],
  [63, 'Sit-Up', 'core', 'bodyweight', [['core', 'primary']]],
  [64, 'Russian Twist', 'core', 'bodyweight', [['core', 'primary']]],
  [65, 'Ab Wheel Rollout', 'core', 'bodyweight', [['core', 'primary']]],
  [66, 'Mountain Climbers', 'core', 'bodyweight', [['core', 'primary'], ['shoulders', 'secondary']]],

  // ---- CARDIO / FULL BODY ----
  [67, 'Treadmill Run', 'cardio', 'cardio_machine', [['quads', 'secondary'], ['hamstrings', 'secondary'], ['calves', 'secondary']]],
  [68, 'Rowing Machine', 'cardio', 'cardio_machine', [['back', 'secondary'], ['quads', 'secondary'], ['hamstrings', 'secondary']]],
  [69, 'Stationary Bike', 'cardio', 'cardio_machine', [['quads', 'secondary'], ['calves', 'secondary']]],
  [70, 'Kettlebell Swing', 'full_body', 'kettlebell', [['glutes', 'primary'], ['hamstrings', 'primary'], ['shoulders', 'secondary'], ['core', 'secondary']]],
  [71, 'Burpee', 'full_body', 'bodyweight', [['quads', 'primary'], ['chest', 'secondary'], ['shoulders', 'secondary'], ['core', 'secondary']]],
  [72, 'Barbell Clean and Press', 'full_body', 'barbell', [['shoulders', 'primary'], ['quads', 'secondary'], ['back', 'secondary']]],
  [73, "Farmer's Carry", 'full_body', 'dumbbell', [['forearms', 'primary'], ['traps', 'secondary'], ['core', 'secondary']]],
  [74, 'Thruster', 'full_body', 'dumbbell', [['quads', 'primary'], ['shoulders', 'secondary'], ['core', 'secondary']]],
];
